# Generated by Django 4.2.6 on 2023-10-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_person_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profile_path',
            field=models.URLField(blank=True),
        ),
    ]
