# Generated by Django 4.2.6 on 2023-10-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_job_profile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='poster_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
