# Generated by Django 4.2.6 on 2023-10-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_person_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
